### ISSUE TITLE
No hay High Score

### ISSUE THREAD

**Issue by matiuri** [danirod/rectball#22]
En estadísticas no se muestra la puntuación más alta; solo se ve la total.

**Comment by matiuri** [comment]
También debería mostrar el récord de tiempo

**Comment by danirod** [comment]
*agrego un "enhancement" para que se vea que es una buena idea*

**Comment by hugomartin89** [comment]
Es realmente un bug como tal?

**Comment by danirod** [comment]
Ahora que lo pienso, no.

Igualmente no estaría mal que se viese, ya puestos a mostrar datos. Como quiero hacer más cambios estéticos a la pantalla de estadísticas (mostrar la canica junto al color, ordenar por cantidad...) no cuesta nada introducirlo a la vez.
