### ISSUE TITLE
Sugerencia en Estadísticas

### ISSUE THREAD

**Issue by matiuri** [danirod/rectball#27]
Los ***Datos por colores*** y los ***Datos por tamaño*** deberían ordenarse según el valor de la estadística.
*Ejemplo:*
* *Verde 23*
* *Azul 19*
* *Rojo 16*
* *Amarillo 16*

*Si tienen el mismo valor, da igual cual va antes o después.*

**Comment by santiagofranco** [comment]
lo pongo aqui para no crear un issue nuevo:

el titulo de la pantalla de estadisticas esta en ingles y todo lo demas en español
PD: no se si esta pensado asi

**Comment by danirod** [comment]
Hola @santiagofranco. Es un bug. Ya ha sido reportado y parcheado. La snapshot de desarrollo actual ya lo tiene corregido y saldrá junto con la Beta 3 el próximo viernes.
