### ISSUE TITLE
Game wrongly resumes on Android when activity changes during pause

### ISSUE THREAD

**Issue by danirod** [danirod/rectball#33]
Source:
* https://twitter.com/josecodfacilito/status/653889714462826496
* https://twitter.com/josecodfacilito/status/653889928934346752

Reproducible steps: During the game press BACK to show the leave dialog. Now, go press HOME to go back your home screen to hide Rectball. Show Rectball again. The game is resumed, while the "leave dialog?" is still visible.

Expected behaviour: the game should not resume because the leave dialog is still visible.

**Comment by hugomartin89** [comment]
It affects desktop version too

**Comment by danirod** [comment]
Yup, noticed this while fixing. Adding the tag for the sake of adding tags.
