### ISSUE TITLE
Pedir doble confirmación antes de abandonar la partida

### ISSUE THREAD

**Issue by matiuri** [danirod/rectball#37]
Muchas veces pasa que uno pausa un juego, y al volver le da a salir sin querer, por lo que propongo doble confirmación. Al apretar sí, que aparezca un cartel de *¿Estás seguro?* con los botones invertidos.

**Comment by danirod** [comment]
Eso ya es pedir por pedir, creo yo. En la 0.3 sólo se puede salir del juego sin querer en el menú inicio. En el resto de pantallas si se pulsa atrás se sale a la pantalla anterior (de opciones a inicio, etc). Si le das a atrás en el menú inicio no te pierdes nada tampoco. Le vuelves a dar en el icono que *porsupuestísimo deberías tener* en tu homescreen y ya xD

¿Algún motivo más serio o puedo declararlo *wontfix* ya?

**Comment by matiuri** [comment]
Me refería a la pantalla de juego. SOLO a la pantalla de juego. Así no salís sin querer y perdés el record. Nunca me refería a salir de la aplicación,

**Comment by danirod** [comment]
Ah vale, estaba malentendiendo.

**Comment by danirod** [comment]
Te estás refiriendo por lo tanto a que si pausas (entendiendo pausar como me voy un momento a mirar otra cosa en el movil y cambio otra vez a la pantalla de juego) no te haga salir sin querer.

**Comment by matiuri** [comment]
Me refiero a que a veces las neuronas no se conectan bien y en vez de tocar no, tocas sí cuando querías tocar no. Entonces que pida doble confirmación al abandonar partida. Y con pausa me refiero a cuando está el cartel de *Leave game?* que aparece al tocar el botón *back*

**Comment by danirod** [comment]
Voy a cambiarlo por lo siguiente.

Juego en pausa
Continuar – Abandonar

Si le dices Abandonar:
¿Quieres salir?
Sí – No

Las cadenas nuevas que voy a meter son:

game.paused=Game paused
game.continue=Continue
game.leaveGame=Leave game

game.paused=Juego en pausa
game.continue=Continuar
game.leaveGame=Abandonar

Por si existe alguna localización particular para es_AR, es buen momento para que la digas y la agregue. Lo incorporo ahora, y el siguiente commit ya es que el que actualiza los códigos de versión a 0.3.0/18.

**Comment by matiuri** [comment]
En este caso es y es_AR son lo mismo
