### ISSUE TITLE
Tiempo mal mostrado en estadísticas

### ISSUE THREAD

**Issue by matiuri** [danirod/rectball#38]
El tiempo total jugado, en la pantalla de estadísticas, aparece solo en minutos y segundos, y me parece que estaría bien que se dividiera también en horas. Así, en vez de mostrar *61:15*, que se muestre *1:01:15*.

**Comment by danirod** [comment]
Ya llevas más de una hora jugada? Wow. Bueno, luego le pongo los tags.

---
E-mail enviado desde un teléfono móvil.

El 16/10/2015 15:26, Matías Steinberg <notifications@github.com> escribió:
El tiempo total jugado, en la pantalla de estadísticas, aparece solo en minutos y segundos, y me parece que estaría bien que se dividiera también en horas. Así, en vez de mostrar *61:15*, que se muestre *1:01:15*.

---
Reply to this email directly or view it on GitHub:
https://github.com/danirod/rectball/issues/38

**Comment by matiuri** [comment]
No es un bug?

**Comment by danirod** [comment]
Realmente no. Lo puse en minutos con toda la consciencia del mundo.
