### ISSUE TITLE
Jugada final

### ISSUE THREAD

**Issue by santiagofranco** [danirod/rectball#44]
La jugada que te muestra al finalizar el tiempo no siempre es la mejor o la más amplia. Parece ser que es la primera que encuentra.

Caso de prueba: encontrar una combinación bastante grande y pulsar solo tres esquinas, esperar a que finalice el tiempo, a veces mostrará la combinación que tenemos medio pulsada y otras una más pequeña.

PD: Me extraña que nadie lo haya visto antes por eso no se si realmente que muestre la primera que encuentre sea el comportamiento programado o de verdad es un bug. 
PD2: Perdón por molestar al creador estando en clase xD.

**Comment by danirod** [comment]
Es programado realmente. En la última versión (0.4.0, código aún no compartido en GitHub), el buscador de combinaciones tiene varios métodos: uno para encontrar la mejor combinación (la que más puntos dará), otra para encontrar la peor combinación (la que menos puntos dará) y una que te da una combinación cualquiera.

La mejor combinación la uso para otorgar bonificaciones si tienes varias y haces la mejor de todas (¡qué menos!), pero para el botón “HINT” y para mostrar la combinación cuando pierdes uso el que da una combinación cualquiera.

TL;DR: Es una cuestión de diseño.

---
Dani Rodríguez <danirod@outlook.com>
Enviado a través de Mail para Mac.
