### ISSUE TITLE
marcador de tiempo

### ISSUE THREAD

**Issue by JuanMansilla** [danirod/rectball#45]
He notado que cuando pides ayuda y estas muy cerca de acabar el tiempo este se sale del rectángulo amarillo.

**Comment by danirod** [comment]
Me lo comentaron hace unas horas. Está parcheado ya y saldrá en las próximas 48 horas como parte de una actualización extra (0.4.1). Dejo abierto este issue mientras tanto por si acaso.

**Comment by danirod** [comment]
Se está subiendo la 0.4.1, por lo que ya puedo dar este problema por arreglado.
