### ISSUE TITLE
Sugerencia con los Perfect

### ISSUE THREAD

**Issue by matiuri** [danirod/rectball#49]
Ya que los **Perfect** son **Perfect**, se me ocurre que rellenen todo el temporizador, a forma de premio.

**Comment by danirod** [comment]
¿Conseguiste hacer uno ya? Yo me he tirado toda la mañana intentándolo, pero no es fácil hacerlo aposta :P

**Comment by matiuri** [comment]
Hice varios en ésta versión. Según mis *stats* totales, hice 31 6x6
