### ISSUE TITLE
Botón de ayuda bugeado

### ISSUE THREAD

**Issue by Guerra24** [danirod/rectball#52]
El boton de ayuda se bugea y marca un rectángulo falso. Para hacer el bug basta con darle al botón ayuda de forma continua mientras al mismo tiempo lo resuelves, al 3 o 4 rectángulo resuelto se bugeara y mostrara la forma del antiguo rectángulo, esta forma también se marca como correcta al acabar el tiempo, aunque no lo sea.

**Comment by Guerra24** [comment]
PD: En android

**Comment by danirod** [comment]
Ya veo.

**Comment by danirod** [comment]
Parece que había una condición de carrera. Primero se ponía a `null` la combinación que baila y luego se ponía a regenerar un nuevo tablero. Si pulsas el botón <?> justo entre medias de que ocurre esas dos cosas, se calcula una nueva pista usando el tablero antiguo, por eso la combinación que baila en la siguiente jugada no es la válida.

Arreglado haciendo que se `null`ifique la combinación que baila **después** de regenerar el tablero.
