### ISSUE TITLE
Botón de ayuda bugeado 2

### ISSUE THREAD

**Issue by Guerra24** [danirod/rectball#53]
Este causa que Rectball se vuelva loco. Como hacerlo, se inicia un juego nuevo, hay que esperar a que la barra del tiempo este justo debajo del botón de ayuda, cuando pase esto le empezamos a dar a la ayuda sin parar hasta que salga la ventana de perdiste el juego y le damos  repetir, entonces se volverá loco. Ojo, no le debemos dar al botón ayuda ninguna sola vez antes de que llegue la barra del tiempo a donde dije. En android.

**Comment by danirod** [comment]
Bien. Bien.
Había visto este bug en el pasado de forma accidental pero nunca fui capaz de averiguar lo que hice para reproducirlo. Ahora ya sé cómo reproducirlo.

**Comment by danirod** [comment]
Arreglado temporalmente introduciendo una llamada a ``clearActions`` en el runnable de la acción que hace que salte a la pantalla de gameover tras terminar una partida. Se estaba llamando de nuevo la acción. Aunque es cierto que todo el sistema de acciones que tengo montado en la GameScreen está roto y debe ser organizado.
