### ISSUE TITLE
Navigation bar doesn't dissapear on inmersive mode

### ISSUE THREAD

**Issue by danirod** [danirod/rectball#54]
This issue is imported from Twitter: https://twitter.com/falvarez/status/663984923775254529

![Navigation bar in inmersive mode](https://pbs.twimg.com/media/CTbyw0hW4AAWwHe.png)

When the game is minimized by pressing HOME and then restored there is a chance on inmersive phones that the navigation bar will stay sticky and hide part of the board. It is reproducible. I can test this by opening the Development settings on my phone and checking "Don't keep activities" so that they are destroyed when they go to background. I can see it happening on my phone after opening Rectball a second time. Should check this.

**Comment by matiuri** [comment]
Hay un fallo en el título: no es *not dissapears*, sino *don't dissapear*.

**Comment by danirod** [comment]
Fixed for Rectball 0.4.4.
