### ISSUE TITLE
Cambiar los colores y la fuente de la pagina

### ISSUE THREAD

**Issue by deathnot3** [danirod/rectball#74]
Debo cambiar los colores y la fuente que se usan en la pagina por aquellos corporativos que usa la empresa en sus anuncios.

- [ ] Cambiar los colores.
- [ ] Cambiar las fuentes de la pagina.

**Comment by danirod** [comment]
Diría que te ha quedado clara la lección 28 😆. Ahora terminaré el trabajo aplicando lo que se enseña en la lección 30 😉.

Duplicated of jgonza22/pagina-web#1
