### ISSUE TITLE
I don't understand kotlin, if the Java language is good

### ISSUE THREAD

**Issue by tianshaokai** [danirod/rectball#80]
I recently wanted to do a game app, and I don't know if libgdx can make the following screenshots.

![image](https://user-images.githubusercontent.com/6706496/34320258-a4d7f770-e830-11e7-80dd-e709647590c0.png)

**Comment by danirod** [comment]
It is very possible, but graphics are harder than code. Kenney does very good graphics. Look at this masterpiece: https://opengameart.org/users/kenney. He makes some assets for free.
