### ISSUE TITLE
Gradle Sync ERROR: Cannot change attributes of configuration ':app:kapt' after it has been resolved

### ISSUE THREAD

**Issue by lastpeony** [danirod/rectball#93]
I am trying to compile and run this on my phone. I do not need any google play services i am just trying to run the basic game.Is there a shortcut to disable them ? 

Anyway this is my build.gradle:
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

configurations {
    natives
}

android {

    compileSdkVersion 27
    buildToolsVersion "27.0.3"
    defaultConfig {
        applicationId "es.danirod.rectball.android"
        minSdkVersion 14
        targetSdkVersion 27
        versionCode 423
        versionName "0.4.11"
    }
    lintOptions {
        abortOnError false
    }
    buildTypes {
        release {
            buildConfigField "boolean", "FINE_DEBUG", "false"
            buildConfigField "boolean", "ANALYTICS_DRY_RUN", "false"
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            buildConfigField "boolean", "FINE_DEBUG", "true"
            buildConfigField "boolean", "ANALYTICS_DRY_RUN", "true"
            versionNameSuffix "-dev"
        }
    }
    /*
     * Support multiple product flavours in order to have two builds. The default one is the
     * GPE (Google Play Edition). This is the flavour you download from the Google Play Store.
     * However, there is the OSP (Open Source Project), which has the same features but it is
     * not linked against Google Play SDK nor Firebase SDK, therefore it doesn't depend on
     * non-free components.
     *
     * People who don't want non-free in their coffee should build the OSP version. In fact,
     * the GPE version will probably fail to build unless you provide the API keys for the SDKs
     * and I'm not sharing these in the repository.
     */
    flavorDimensions "channel"
    productFlavors {
        gpe {
            dimension "channel"

            // No version name suffix because this is the default version.
        }
        osp {
            dimension "channel"

            // Mark this version as the Open Source Project.
            versionNameSuffix "-OSP"
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')

    // libGDX
    compile "com.badlogicgames.gdx:gdx-backend-android:$libgdx_version"
    compile "com.badlogicgames.gdx:gdx-freetype:$libgdx_version"
    natives "com.badlogicgames.gdx:gdx-platform:$libgdx_version:natives-armeabi"
    natives "com.badlogicgames.gdx:gdx-platform:$libgdx_version:natives-armeabi-v7a"
    natives "com.badlogicgames.gdx:gdx-platform:$libgdx_version:natives-x86"
    natives "com.badlogicgames.gdx:gdx-freetype-platform:$libgdx_version:natives-armeabi"
    natives "com.badlogicgames.gdx:gdx-freetype-platform:$libgdx_version:natives-armeabi-v7a"
    natives "com.badlogicgames.gdx:gdx-freetype-platform:$libgdx_version:natives-x86"

    // Google Play Services are required on the Google Play version.
    gpeCompile "com.google.android.gms:play-services-analytics:17.0.0"
    gpeCompile "com.google.android.gms:play-services-games:19.0.0"
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
}

// Extract the libGDX natives from the JARs.
task copyAndroidNatives() {
    file("src/main/jniLibs/armeabi/").mkdirs();
    file("src/main/jniLibs/armeabi-v7a/").mkdirs();
    file("src/main/jniLibs/x86/").mkdirs();

    configurations.natives.files.each { jar ->
        def outputDir = null
        if(jar.name.endsWith("natives-armeabi-v7a.jar")) outputDir = file("src/main/jniLibs/armeabi-v7a")
        if(jar.name.endsWith("natives-armeabi.jar")) outputDir = file("src/main/jniLibs/armeabi")
        if(jar.name.endsWith("natives-x86.jar")) outputDir = file("src/main/jniLibs/x86")
        if(outputDir != null) {
            copy {
                from zipTree(jar)
                into outputDir
                include "*.so"
            }
        }
    }
}
repositories {
    mavenCentral()
}

apply plugin: 'com.google.gms.google-services'
```

ERROR: Cannot change attributes of configuration ':app:kapt' after it has been resolved

Full error:
https://pastebin.com/2J3Zx9HX

Another thing is i realized that this projects structure is different than a regular libgdx project. Can someone simply explain me the entrance point of the basic game so that maybe i can move source files to regular libgdx project and compile by using that way because i found project way too complicated with unnecessary stuff for someone who is just looking forward to learn from open source libgdx project.As you see i couldnt even compile it :(

thanks

**Comment by danirod** [comment]
Hi. Which flavour are you using to build the game? Make sure you are explicitly using the osp flavour, otherwise it will use or include the gpe flavour which uses all the Google SDK crap.

**Comment by danirod** [comment]
> Another thing is i realized that this projects structure is different than a regular libgdx project.

That's because this is not a libGDX project, it's an Android project that has libGDX as a dependency. It used to be a libGDX project, but supporting desktop requires stubbing a lot of Android stuff that is embedded into the game (such as the sharing intent for sharing a screenshot of the scoreboard, or opening the Google Play Store).

In other words, if you are looking to learn from an open source libGDX project you should not use this. I have another project that uses a regular libGDX project and that **it is more updated than this one** that you can use as a reference if you wish: http://github.com/danirod/jumpdontdie

**Comment by danirod** [comment]
> As you see i couldnt even compile it :(

Indeed. It is too difficult to keep up with changes made to the gradlescripts provided by the Android SDK, and I've never liked Android Studio and how it tears my computer down (CPU, disk size) every time I install it. In the end I'm still fed up with spending weeks trying to fix Rectball and other Android projects, just to have them break them again every year whenever they release a new Android version / Android Studio version / SDK platform version.

**Comment by lastpeony** [comment]
i extracted core game code and removed most of the parts and compiled it with clean libgdx project. i guess this is enough for me now since game is working fine.

**Comment by danirod** [comment]
Cool. Can this ticket be marked as solved then, or is there anything else pending?

**Comment by lastpeony** [comment]
yes thanks for answering

**Comment by danirod** [comment]
Thanks to you for checking out the project :)
